# openai_configs.yaml  (kept in client_configs/)
gpt-4.1-standard:
  - client_class: "openai.AzureOpenAI"
    azure_deployment: "gpt-4.1-standard"
    azure_endpoint: "https://ai-olmohub1163464654570.openai.azure.com/"
    api_version: "2025-04-14-preview"
    api_key: "${AZURE_API_KEY}"