weighted_alpaca_eval_gpt4.1_azure:
  prompt_template: "alpaca_eval_clf_gpt4_turbo/alpaca_eval_clf.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4.1-standard"
    max_tokens: 1
    temperature: 1 # temperature should be applied for sampling, so that should make no effect.
    logprobs: true
    top_logprobs: 5
    # tell alpaca_eval to use the Azure client
    client_class: "openai.AzureOpenAI"
    # kwargs that will be passed to openai.AzureOpenAI(**client_kwargs)
    client_kwargs:
      azure_deployment: "gpt-4.1-standard"
      azure_endpoint: "https://ai-olmohub1163464654570.openai.azure.com/"
      api_version: "2024-03-01-preview"
      api_key: "${AZURE_API_KEY}"          # env-var expansion works
  fn_completion_parser: "logprob_parser"
  completion_parser_kwargs:
    numerator_token: "m"
    denominator_tokens: ["m", "M"]
    is_binarize: false
  completion_key: "completions_all"
  batch_size: 1
  # client_class: "openai.AzureOpenAI"
  # client_kwargs:
  #   azure_deployment: "gpt-4.1-standard"
  #   api_key: $AZURE_API_KEY
  #   azure_endpoint: "https://ai-olmohub1163464654570.openai.azure.com/ "
  #   api_version: "2024-03-01-preview"
